# Generated by Django 2.2 on 2019-04-19 06:54

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Custody',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.CharField(max_length=200)),
                ('serialNum', models.CharField(max_length=100)),
                ('createdAt', models.DateTimeField(default=datetime.datetime.now)),
            ],
        ),
    ]
