# Generated by Django 2.2 on 2019-04-19 07:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('custodies', '0002_custody_employee'),
    ]

    operations = [
        migrations.RenameField(
            model_name='custody',
            old_name='createdAt',
            new_name='created_at',
        ),
        migrations.RenameField(
            model_name='custody',
            old_name='serialNum',
            new_name='serial_number',
        ),
    ]
